# Generated by Django 5.0.6 on 2024-06-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="category",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="imageUrl",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewCount",
            field=models.IntegerField(null=True),
        ),
    ]